[[main]]
  name = "About"
  url = "#section-about"
  weight = 10

[[main]]
  name = "News"
  url = "#section-news"
  weight = 20

[[main]]
  name = "Research"
  url = "#section-research"
  weight = 30

[[main]]
  name = "Publications"
  url = "#section-publication"
  weight = 40

[[social]]
  name = "Google Scholar"
  pre = '<i class="fa-solid fa-graduation-cap fa-fw"></i>'
  url = "https://scholar.google.com/citations?user=HrJ7_4oAAAAJ&hl=en"
  weight = 20
  [social.params]
    target = "_blank"

# [[social]]
#   name = "ORCiD"
#   pre = '<i class="fa-brands fa-orcid fa-fw"></i>'
#   url = "https://orcid.org/0000-0002-4242-8879"
#   weight = 15
#   [social.params]
#     target = "_blank"

[[social]]
  name = "LinkedIn"
  pre = '<i class="fa-brands fa-linkedin-in fa-fw"></i>'
  url = "https://www.linkedin.com/in/yuyangucsb/"
  weight = 30
  [social.params]
    target = "_blank"

[[social]]
  name = "GitHub"
  pre = '<i class="fa-brands fa-github fa-fw"></i>'
  url = "https://github.com/wyywyy23/"
  weight = 40
  [social.params]
    target = "_blank"

[[social]]
  name = "Curriculum Vitae"
  pre = '<i class="ai ai-cv ai-fw"></i>'
  url = "/cv/"
  weight = 10