# Meta Data for SEO

## Homepage
title = "Yuyang Wang"
titlenative = "王昱阳"
titleSeparator = "-"
titleAddition = "Academic Homepage"
description = "Yuyang Wang is a Postdoctoral Research Scientist in the Lightwave Research Laboratory at Columbia University."

## Open Graph
images = ["android-chrome-512x512.png"]
ogLocale = "en_US"
domainTLD = "wyywyy23.github.io"
titleHome = "Yuyang Wang - Academic Homepage"

## Twitter Cards
twitterSite = "@wyywyy23"
twitterCreator = "@wyywyy23"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Yuyang Wang"
schemaAuthor = "Yuyang Wang"
schemaAuthorTwitter = "https://twitter.com/wyywyy23"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/yuyangucsb/"
schemaAuthorGitHub = "https://github.com/wyywyy23"
schemaLocale = "en-US"
schemaLogo = "android-chrome-512x512.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "android-chrome-512x512.png"
schemaImageWidth = 512
schemaImageHeight = 512
schemaTwitter = "https://twitter.com/wyywyy23"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/wyywyy23/wyywyy23.github.io"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images - Temporarily left in place for backward compatibility
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "600"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "green-sea-turtle-hatchling.jpg" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "© 2023 Yuyang Wang. Powered by <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a> and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"

# Feed
copyRight = "© 2023 Yuyang Wang."

# Alert
alert = false
alertDismissable = true
# alertText = "Help Doks grow by supporting us on Open Collective. <a class=\"alert-link stretched-link\" href=\"https://opencollective.com/doks\" target=\"_blank\" rel=\"noopener\">Become a backer!</a>"
# alertText = "Better UX navigation, multilingual and i18n support, and more. <a class=\"alert-link stretched-link\" href=\"/blog/doks-v0.3/\">Check out what's new!</a>"
alertText = "The Jamstack at Scale: Building Sites for Audiences of Millions. <a class=\"alert-link stretched-link\" href=\"https://www.netlify.com/resources/ebooks/jamstack-at-scale?utm_campaign=Website%20-%20Whitepaper%20-%20Jamstack%20at%20Scale&utm_source=Homepage%20Announcement%20Bar\">Get the eBook!</a>"
# alertText = "Multi level section menu — <strong>automatically</strong> generated, and more. <a class=\"alert-link stretched-link\" href=\"/blog/doks-v0.4/\">Check out what's new!</a>"
# alertText = "What Doks future features are important to you? <a class=\"alert-link stretched-link\" href=\"https://docs.google.com/forms/d/e/1FAIpQLSe0DItAFv2cNSC0S_L6DQBw9ofB0ogYvZqeoWHHRX-Aal-5zQ/viewform?usp=sf_link\" target=\"_blank\" rel=\"noopener\">Take the 2021 Doks Survey</a>"

# Edit Page
docsRepo = "https://github.com/wyywyy23/wyywyy23.github.io"
editPage = true

# Embed PDF
adobeClientId = "be618191765442f6a55213d23aca9286"
adobeClientIdLocal = "f9d76183958747e59cd1303f1bff65f9"

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  darkMode = true
  bootStrapJs = true
  highLight = true
  multilingualMode = false # Not yet functional
  docsVersioning = false # Not yet functional
  kaTex = true

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true

# lazyimg
[lazyimg]
  resizer = "auto"
  renderer = "lqip-webp"

  # Resizer options:
  lqipSize = "120x Gaussian"
  maxSize = "1920x"
  responsiveSizes = [ "320x", "640x", "768x", "1024x", "1366x", "1600x", "1920x" ]
  resizeOptions = "Lanczos q95"

  # Renderer options:
  class = "img-fluid"
  # alt = ""
  noscript = true

  errorHandler = "warning"