[[docs]]
  name = "Prologue"
  weight = 10
  identifier = "prologue"
  url = "/docs/prologue/"

[[docs]]
  name = "Help"
  weight = 60
  identifier = "help"
  url = "/docs/help/"

# [[docs]]
#   name = "Lorem"
#   weight = 70
#   identifier = "lorem"
#   url = "/docs/lorem/"

[[guide]]
  name = "Lorem"
  weight = 10
  identifier = "lorem"
  url = "/guide/lorem/"

[[tutorial]]
  name = "Lorem"
  weight = 10
  identifier = "lorem"
  url = "/tutorial/lorem/"

[[main]]
  name = "Docs"
  url = "/docs/prologue/introduction/"
# url = "/docs/1.0/prologue/introduction/"
  weight = 10

# [[main]]
#   name = "Tutorial"
#   url = "/tutorial/lorem/ipsum/"
#   weight = 15

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 20

[[main]]
  name = "Get Started"
  weight = 30
  identifier = "get-started"
  url = "/docs/prologue/introduction/"

[[main]]
  name = "Quick Start"
  weight = 40
  identifier = "quick-start"
  url = "/docs/prologue/quick-start/"
  parent = "get-started"

[[main]]
  name = "Tutorial"
  weight = 50
  identifier = "tutorial"
  url = "https://getdoks.org/tutorial/introduction/"
  parent = "get-started"

[[social]]
  name = "Google Scholar"
  pre = "<span style=\"vertical-align: -.125em; fill: currentColor;\"> <i class=\"fas fa-graduation-cap fa-fw\"></i> </span>"
  url = "https://scholar.google.com/citations?user=HrJ7_4oAAAAJ&hl=en"
  weight = 10

# [[social]]
#   name = "ORCiD"
#   pre = "<span style=\"vertical-align: -.125em; fill: currentColor;\"> <i class=\"fab fa-orcid fa-fw\"></i> </span>"
#   url = "https://orcid.org/0000-0002-4242-8879"
#   weight = 15

[[social]]
  name = "LinkedIn"
  pre = "<span style=\"vertical-align: -.125em; fill: currentColor;\"> <i class=\"fab fa-linkedin-in fa-fw\"></i> </span>"
  url = "https://www.linkedin.com/in/yuyangucsb/"
  weight = 20

[[social]]
  name = "GitHub"
  pre = "<span style=\"vertical-align: -.125em; fill: currentColor;\"> <i class=\"fab fa-github fa-fw\"></i> </span>"
  url = "https://github.com/wyywyy23/"
  weight = 30

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
